create table student (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	phone_number VARCHAR(50),
	country VARCHAR(50)
);
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (1, 'Alisa', 'Thalmann', 'athalmann0@tuttocitta.it', 'Agender', null, 'Moldova');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (2, 'Flor', 'Tomkins', 'ftomkins1@nytimes.com', 'Female', '(259) 3667647', 'Azerbaijan');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (3, 'Raquela', 'Jersh', 'rjersh2@phoca.cz', 'Female', '(187) 9316926', null);
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (4, 'Alard', 'Thirsk', 'athirsk3@census.gov', 'Male', '(433) 3440479', 'Costa Rica');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (5, 'Blondelle', 'Dubber', 'bdubber4@businessweek.com', 'Female', '(290) 2820549', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (6, 'Kiel', 'Archibould', 'karchibould5@seattletimes.com', 'Male', '(793) 3557531', 'Azerbaijan');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (7, 'Dacy', 'Lenox', 'dlenox6@chron.com', 'Female', '(822) 8817783', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (8, 'Shauna', 'Driutti', null, 'Female', '(438) 6998994', 'Moldova');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (9, 'Carena', 'Ambroz', null, 'Female', '(664) 7398053', 'Nepal');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (10, 'Pavlov', 'Biskupski', 'pbiskupski9@youku.com', 'Male', '(419) 1703639', 'Georgia');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (11, 'Shelden', 'Matusevich', 'smatusevicha@bloglines.com', 'Male', '(765) 9382644', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (12, 'Vikky', 'Coil', 'vcoilb@lulu.com', 'Female', null, 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (13, 'Laurel', 'Songest', null, 'Female', null, 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (14, 'Arnie', 'Pedron', 'apedrond@goo.ne.jp', 'Male', '(489) 4955885', 'Moldova');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (15, 'Renell', 'Beernt', 'rbeernte@icq.com', 'Female', '(185) 9623055', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (16, 'Jennilee', 'Cock', 'jcockf@scribd.com', 'Female', '(887) 5427013', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (17, 'Dougy', 'Huckle', 'dhuckleg@lycos.com', 'Male', '(734) 7478128', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (18, 'Brantley', 'Longhirst', 'blonghirsth@shutterfly.com', 'Male', null, 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (19, 'Wittie', 'Culbert', 'wculberti@topsy.com', 'Male', '(764) 5455143', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (20, 'Nickola', 'Genge', 'ngengej@europa.eu', 'Male', '(268) 1408690', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (21, 'Cordelia', 'Moughton', 'cmoughtonk@etsy.com', 'Female', null, 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (22, 'Morgen', 'Mateos', 'mmateosl@quantcast.com', 'Male', '(763) 3168265', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (23, 'Hillie', 'Lyes', 'hlyesm@cbslocal.com', 'Male', '(934) 4859483', null);
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (24, 'Alva', 'Novotni', 'anovotnin@123-reg.co.uk', 'Male', '(274) 7144310', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (25, 'Bastien', 'McGloin', 'bmcgloino@behance.net', 'Male', '(388) 9195210', 'Azerbaijan');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (26, 'Janette', 'Brockherst', null, 'Female', null, 'Costa Rica');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (27, 'Peggie', 'Ellacott', 'pellacottq@cbsnews.com', 'Female', '(541) 2659336', 'Azerbaijan');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (28, 'Orella', 'Broadstock', 'obroadstockr@dedecms.com', 'Female', '(345) 4725558', null);
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (29, 'Rollins', 'Ruggen', 'rruggens@abc.net.au', 'Male', '(302) 4466872', 'Azerbaijan');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (30, 'Ardelis', 'Baldinotti', null, 'Female', '(769) 1825581', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (31, 'Elvera', 'Holywell', 'eholywellu@paypal.com', 'Female', '(475) 2848000', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (32, 'Barrett', 'Braznell', 'bbraznellv@apache.org', 'Male', '(412) 6855655', 'Moldova');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (33, 'Malina', 'McKelvey', 'mmckelveyw@google.nl', 'Female', '(707) 5886925', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (34, 'Verne', 'McArthur', 'vmcarthurx@msn.com', 'Male', null, 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (35, 'Tymothy', 'Lanney', 'tlanneyy@smh.com.au', 'Agender', '(328) 4515921', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (36, 'Gallagher', 'Enefer', 'geneferz@cnbc.com', 'Male', '(898) 8923836', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (37, 'Shurwood', 'Trevino', 'strevino10@samsung.com', 'Non-binary', '(895) 4663349', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (38, 'Lemuel', 'Soaper', 'lsoaper11@soundcloud.com', 'Male', '(332) 7698748', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (39, 'Idell', 'McGraw', 'imcgraw12@163.com', 'Female', '(357) 2889194', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (40, 'Eugenie', 'Burriss', 'eburriss13@hexun.com', 'Female', '(483) 5695306', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (41, 'Hal', 'Ciccoloi', 'hciccoloi14@yolasite.com', 'Male', null, 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (42, 'Rozanne', 'Hasnney', null, 'Female', '(510) 9468953', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (43, 'Harold', 'Ravenshaw', null, 'Male', '(381) 9458067', 'Georgia');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (44, 'Oren', 'Turl', null, 'Male', '(977) 7503375', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (45, 'Tova', 'Antonikov', 'tantonikov18@yahoo.com', 'Female', '(222) 3635577', 'Moldova');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (46, 'Judas', 'Mettericke', 'jmettericke19@tuttocitta.it', 'Genderfluid', '(141) 2645595', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (47, 'Jazmin', 'Sherwyn', 'jsherwyn1a@goo.gl', 'Female', '(777) 8128035', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (48, 'Buiron', 'Bowring', 'bbowring1b@github.io', 'Male', null, 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (49, 'Aleece', 'Lowthian', 'alowthian1c@ehow.com', 'Female', '(621) 8220430', 'Moldova');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (50, 'Brinn', 'Sear', 'bsear1d@bbc.co.uk', 'Non-binary', null, 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (51, 'Rennie', 'Barbery', 'rbarbery1e@bloomberg.com', 'Female', null, 'Moldova');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (52, 'Walton', 'Pendlenton', 'wpendlenton1f@ca.gov', 'Male', '(224) 5370169', null);
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (53, 'Selene', 'Shurville', null, 'Bigender', '(742) 9220085', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (54, 'Steward', 'Stirzaker', null, 'Non-binary', null, 'Moldova');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (55, 'Stillmann', 'Bradnock', 'sbradnock1i@sogou.com', 'Male', '(538) 4539080', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (56, 'Albina', 'Bycraft', 'abycraft1j@go.com', 'Female', '(888) 1194261', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (57, 'Frasquito', 'Raynton', 'fraynton1k@over-blog.com', 'Male', '(552) 1885881', 'Georgia');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (58, 'Emanuele', 'Ebbens', 'eebbens1l@rediff.com', 'Male', '(146) 6578513', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (59, 'Aguistin', 'Badland', 'abadland1m@aboutads.info', 'Male', '(148) 4097878', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (60, 'Margot', 'Phippen', 'mphippen1n@drupal.org', 'Female', '(737) 8921054', 'Georgia');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (61, 'Dolf', 'Bingle', 'dbingle1o@chronoengine.com', 'Male', null, 'Azerbaijan');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (62, 'Pearline', 'Pearce', 'ppearce1p@mayoclinic.com', 'Female', '(947) 6907829', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (63, 'Liam', 'Denyukhin', 'ldenyukhin1q@photobucket.com', 'Male', '(815) 4198828', 'Azerbaijan');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (64, 'Ludovico', 'Mottershead', null, 'Male', '(471) 8764859', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (65, 'Normy', 'Durant', 'ndurant1s@stanford.edu', 'Male', '(693) 6047045', 'Costa Rica');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (66, 'Rikki', 'Denial', 'rdenial1t@ucoz.com', 'Female', '(709) 9442552', 'Moldova');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (67, 'Gloria', 'Broader', 'gbroader1u@examiner.com', 'Female', '(196) 4848203', 'Costa Rica');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (68, 'Corliss', 'Mozzini', 'cmozzini1v@springer.com', 'Female', '(834) 6709770', 'Azerbaijan');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (69, 'Marice', 'Frounks', 'mfrounks1w@ow.ly', 'Female', '(992) 4890379', 'Moldova');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (70, 'Poppy', 'Duer', 'pduer1x@xing.com', 'Female', null, 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (71, 'Corliss', 'Malletratt', null, 'Female', '(113) 1116416', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (72, 'Danit', 'Conduit', null, 'Female', '(393) 5349793', 'Costa Rica');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (73, 'Loydie', 'Shipsey', null, 'Male', '(325) 4816913', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (74, 'Hobey', 'Nattriss', 'hnattriss21@hc360.com', 'Male', '(984) 8190420', null);
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (75, 'Ira', 'Wittey', 'iwittey22@slashdot.org', 'Male', '(466) 7304141', 'Azerbaijan');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (76, 'Charissa', 'Whyborne', null, 'Female', '(380) 7668538', 'Azerbaijan');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (77, 'Morry', 'Bosma', 'mbosma24@domainmarket.com', 'Male', '(896) 7548386', 'Nepal');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (78, 'Vannie', 'Gavini', 'vgavini25@nsw.gov.au', 'Female', '(778) 8409072', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (79, 'Rolph', 'Battrick', null, 'Male', '(265) 4202622', 'Azerbaijan');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (80, 'Ethelin', 'Aylwin', 'eaylwin27@histats.com', 'Genderqueer', null, 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (81, 'Cornelle', 'Fatkin', null, 'Female', '(168) 5969593', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (82, 'Lorain', 'Gronow', null, 'Female', '(367) 2291178', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (83, 'Upton', 'Duffell', 'uduffell2a@uol.com.br', 'Male', '(399) 6755107', 'Nepal');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (84, 'Pen', 'Lissaman', 'plissaman2b@cornell.edu', 'Female', '(585) 3193216', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (85, 'Konstanze', 'Caulton', 'kcaulton2c@nyu.edu', 'Female', '(539) 2697568', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (86, 'Simona', 'Sedgman', 'ssedgman2d@sina.com.cn', 'Female', '(915) 6102435', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (87, 'Rand', 'Treslove', null, 'Male', '(234) 8243709', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (88, 'David', 'Bellini', 'dbellini2f@mtv.com', 'Male', '(524) 9768529', 'Costa Rica');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (89, 'Livia', 'Hiddy', 'lhiddy2g@about.me', 'Female', '(178) 2239792', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (90, 'Maximo', 'Gumly', null, 'Male', '(108) 3233406', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (91, 'Ivy', 'Victoria', 'ivictoria2i@accuweather.com', 'Non-binary', null, 'Costa Rica');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (92, 'Alice', 'Bolino', 'abolino2j@scribd.com', 'Female', '(974) 8879784', 'Nepal');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (93, 'Farlay', 'Foxwell', 'ffoxwell2k@delicious.com', 'Male', '(996) 9159722', null);
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (94, 'Myrle', 'Whithalgh', 'mwhithalgh2l@canalblog.com', 'Female', '(930) 8862898', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (95, 'Wilmette', 'Byrd', 'wbyrd2m@over-blog.com', 'Female', '(907) 5694746', null);
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (96, 'Collin', 'Goldspink', 'cgoldspink2n@gravatar.com', 'Male', '(712) 2503567', null);
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (97, 'Byram', 'Kingsly', 'bkingsly2o@so-net.ne.jp', 'Male', '(963) 6885801', 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (98, 'Wat', 'Szwandt', 'wszwandt2p@reuters.com', 'Male', '(331) 2381533', 'Chile');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (99, 'Mia', 'Orsi', 'morsi2q@sitemeter.com', 'Female', null, 'Honduras');
insert into student (id, first_name, last_name, email, gender, phone_number, country) values (100, 'Maribeth', 'Jedrys', 'mjedrys2r@techcrunch.com', 'Female', '(666) 3197838', 'Honduras');